version: "3.8"
services:

    demo-monitoring-app:
        image: "demo-monitoring-app"
        restart: unless-stopped
        expose:
        - "9000"
        ports:
        - "9000:9000"
        labels:
            prometheus-scrape.enabled: "true"
            prometheus-scrape.port: 9000
            prometheus-scrape.job_name: "demo-monitoring-app"
            prometheus-scrape.metrics_path: "/actuator/prometheus"
        networks:
            - internal
            - monitoring_ext

    demo-monitoring-auth:
        image: "demo-monitoring-auth"
        restart: unless-stopped
        expose:
        - "9001"
        ports:
        - "9001:9001"
        labels:
            prometheus-scrape.enabled: "true"
            prometheus-scrape.port: 9001
            prometheus-scrape.job_name: "demo-monitoring-auth"
            prometheus-scrape.metrics_path: "/actuator/prometheus"
        networks:
            - internal
            - monitoring_ext

    demo-monitoring-billing:
        image: "demo-monitoring-billing"
        restart: unless-stopped
        expose:
        - "9002"
        ports:
        - "9002:9002"
        labels:
            prometheus-scrape.enabled: "true"
            prometheus-scrape.port: 9002
            prometheus-scrape.job_name: "demo-monitoring-billing"
            prometheus-scrape.metrics_path: "/actuator/prometheus"
        networks:
            - internal
            - monitoring_ext

    demo-monitoring-content:
        image: "demo-monitoring-content"
        restart: unless-stopped
        expose:
        - "9003"
        ports:
        - "9003:9003"
        labels:
            prometheus-scrape.enabled: "true"
            prometheus-scrape.port: 9003
            prometheus-scrape.job_name: "demo-monitoring-content"
            prometheus-scrape.metrics_path: "/actuator/prometheus"
        networks:
            - internal
            - monitoring_ext

networks:
    internal:
    monitoring_ext:
        external: true
        name: monitoring_ext