version: "3.8"
services:

    demo-monitoring-app:
        image: "demo-monitoring-app"
        restart: unless-stopped
        expose:
        - "9000"
        ports:
        - "9000:9000"
        networks:
            - internal
            - monitoring_ext

    demo-monitoring-auth:
        image: "demo-monitoring-auth"
        restart: unless-stopped
        expose:
        - "9001"
        ports:
        - "9001:9001"
        networks:
            - internal
            - monitoring_ext

    demo-monitoring-billing:
        image: "demo-monitoring-billing"
        restart: unless-stopped
        expose:
        - "9002"
        ports:
        - "9002:9002"
        networks:
            - internal
            - monitoring_ext

    demo-monitoring-content:
        image: "demo-monitoring-content"
        restart: unless-stopped
        expose:
        - "9003"
        ports:
        - "9003:9003"
        networks:
            - internal
            - monitoring_ext

networks:
    internal:
    monitoring_ext:
        external: true
        name: monitoring_ext
